<html>

<head>
<title>Hacked By Parsiland Security Team</title>
</head>

<body bgcolor="#000000">

<p align="center"><font size="5" color="#A3A6CD" face="Tahoma">Hacked 
By</font></p>
<p align="center"><font face="Tahoma"><font color="#8F97D8" size="6">&nbsp;</font><font color="#CFD2F1" size="6">P</font><font color="#8F97D8" size="6">arsiland </font>
<font color="#CFD2F1" size="6">S</font><font color="#8F97D8" size="6">ecurity </font>
<font color="#CFD2F1" size="6">T</font><font color="#8F97D8" size="6">eam</font></font></p>
<p align="center"><font color="#D1D2F1" face="Tahoma">Your B0x 0wned by :</font></p>
<p align="center"><font size="4" color="#BBBCEA" face="Tahoma">&nbsp;M4st3r_4w4r3 , GodMaster , KinG , 
DangerMan , Immortal_Boy</font></p>



<p align="center"><font size="5" color="#BBBCEA" face="Tahoma"> DangerMan</font><font color="#A8ADDF" size="4" face="Tahoma"> was here</font></p>






<p align="center"><font face="Tahoma"><a href="http://www.securItYtEam.Parsiland.com" target="_blank">
<img border="0" src="http://aware.persiangig.ir/other/Parsiland2.JPG" alt=".:: Islamic Republic Of Iran For Ever ::." width="559" height="506"></a></font></p>

<font face="Tahoma">

<! ---------------------------------------------------------------------------------------------------- >

<! go hell !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Y! : Magicp30_ir !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! >

<! ---------------------------------------------------------------------------------------------------- >


</font>
<p align="center"><font color="#BBBCEA" face="Tahoma" size="2">Power By </font>
<font face="Tahoma"><font color="#CFD2F1" size="2">: P</font><font color="#8F97D8" size="2">arsiland </font>
<font color="#CFD2F1" size="2">S</font><font color="#8F97D8" size="2">ecurity </font>
<font color="#CFD2F1" size="2">T</font><font color="#8F97D8" size="2">eam</font></font></p>
<p align="center"><font face="Tahoma" size="2"><font color="#00FF00">Form</font><font color="#FF0000">&nbsp;
</font><font color="#FFFFFF">IRAN</font><font color="#FF0000"> (Islamic 
Republic)</font></font></p>


</body></html>